spring:
  application:
    name: servicesync-api

  # Java 21 optimized JVM settings
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        # Java 21 performance optimizations
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

  datasource:
    url: jdbc:postgresql://localhost:5432/servicesync
    username: ${DB_USERNAME:servicesync}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5

  security:
    jwt:
      secret: ${JWT_SECRET:your-very-secure-secret-key-for-production}
      expiration: 86400000 # 24 hours
      refresh-expiration: 604800000 # 7 days

server:
  port: ${SERVER_PORT:8080}
  # Java 21 Virtual Threads (Project Loom)
  tomcat:
    threads:
      max: 200
      min-spare: 10

# Java 21 specific optimizations
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.hospital.servicesync: ${LOG_LEVEL:DEBUG}
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Custom application properties
app:
  name: ServiceSync
  version: 1.0.0
  features:
    ml-optimization: ${ENABLE_ML:false}
    iot-integration: ${ENABLE_IOT:false}
    advanced-analytics: ${ENABLE_ANALYTICS:true}