# Base configuration - common settings for all environments
spring:
  application:
    name: servicesync-api

  profiles:
    active: local

  # JPA Configuration (common)
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

# Server Configuration
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/json
  error:
    include-message: always
    include-binding-errors: always

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    diskspace:
      enabled: true
    db:
      enabled: true

# Custom Application Properties
app:
  name: ServiceSync
  version: "@project.version@"
  description: Digital hospital meal delivery tracking system
  timezone: Africa/Johannesburg

  # Feature Flags (can be overridden per environment)
  features:
    advanced-analytics: true
    real-time-notifications: true
    file-upload: true

  # File Storage Configuration
  storage:
    local:
      upload-dir: ./uploads
      diet-sheet-dir: ./uploads/diet-sheets
      max-file-size: 5MB

  # Business Rules Configuration
  business:
    session:
      auto-complete-hours: 24
      max-meal-count: 100
    performance:
      target-serving-rate: 0.6
    alerts:
      travel-time-threshold: 900
      nurse-response-threshold: 300
      completion-rate-threshold: 75